basscollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  #? path('[http url]', views.[where in the views file], name='[reference this route from templates]' )
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  #! localhost:8000/basses
  path('basses/', views.basses_index, name='basses_index'),
  path('basses/<int:bass_id>/', views.basses_detail, name='basses_detail'),
  
  # class based view to create basses via form
  path('basses/create/', views.BassCreate.as_view(), name='basses_create'),

  path('basses/<int:pk>/update/', views.BassUpdate.as_view(), name='basses_update'),
  
  path('basses/<int:pk>/delete/', views.BassDelete.as_view(), name='basses_delete'),
  # localhost:8000/basses/int:bass_id/add_musician
  path('basses/<int:bass_id>/add_musician/', views.add_musician, name='add_musician'),
  
  path('basses/<int:bass_id>/assoc_amp/<int:amp_id>', views.assoc_amp, name='assoc_amp'),


  #! /amps
  path('amps/', views.amps_index, name='amps_index'),
  
  path('amps/create/', views.AmpCreate.as_view(), name='amps_create'),
  
  path('amps/<int:amp_id>/', views.amps_detail, name='amps_detail'),
  
  path('amps/<int:pk>/update/', views.AmpUpdate.as_view(), name='amps_update'),

  path('amps/<int:pk>/delete/', views.AmpDelete.as_view(), name='amps_delete'),

  #! /accounts
  path('accounts/signup/', views.signup, name='signup'),

  # ! comma after each route!
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Amp(models.Model):
  manufacturer = models.CharField(max_length=100)
  model_name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.manufacturer + ' ' + self.model_name 

  def get_absolute_url(self):
    return reverse('amps_detail', kwargs={'amp_id': self.id})
    
class Bass(models.Model):
  manufacturer = models.CharField(max_length=100)
  model_name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  amps = models.ManyToManyField(Amp)

  class Meta:  
    verbose_name_plural = 'Basses'

  def __str__(self):
    return self.manufacturer + ' ' + self.model_name

  def get_absolute_url(self):
    return reverse('basses_detail', kwargs={'bass_id': self.id})


class Musician(models.Model):
  name = models.CharField(max_length=100)
  bass = models.ForeignKey(Bass, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

# class Rig(models.Model):
#   name = models.CharField(max_length=100)
#   bass = models.ForeignKey(Bass, on_delete=models.CASCADE)
#   amps = models.ForeignKey(Amp, on_delete=models.CASCADE)
  
#   def __str__(self):
#     return self.name

#   def get_absolute_url(self):
#     return reverse('rigs_index')

# ! need to make migrations

main_app/forms.py
from django.forms import ModelForm
from .models import Musician

class MusicianForm(ModelForm):
  class Meta:
    model = Musician
    fields = ['name']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Bass
from .models import Amp
from .forms import MusicianForm

# home view
def home(request):
  return render(request, 'home.html')


# about view
def about(request):
  return render(request, 'about.html')

#! bass views
@login_required
def basses_index(request):
  # basses = Bass.objects.all()
  basses = Bass.objects.filter(user=request.user)
  return render(request, 'basses/index.html', {'basses':basses})

@login_required
def basses_detail(request, bass_id):
  bass = Bass.objects.get(id=bass_id)
  # Get the amps the bass doesn't have
  amps_bass_doesnt_have = Amp.objects.exclude( id__in = bass.amps.all().values_list('id'))
  print(request.user)
  musician_form = MusicianForm()
  return render(request, 'basses/detail.html', {
    'bass':bass, 'musician_form': musician_form, 'amps': amps_bass_doesnt_have
  })

@login_required
def assoc_amp(request, bass_id, amp_id):
  Bass.objects.get(id=bass_id).amps.add(amp_id)
  return redirect('basses_detail', bass_id=bass_id)

@login_required
def add_musician(request, bass_id):
  form = MusicianForm(request.POST)
  if form.is_valid():
    new_musician = form.save(commit=False)
    new_musician.bass_id = bass_id
    new_musician.save()
  return redirect('basses_detail', bass_id=bass_id)         

class BassCreate(LoginRequiredMixin, CreateView):
  model = Bass
  fields = ['manufacturer', 'model_name', 'description']
  #? alternatively:  fields = ['manufacturer', 'model', 'description']
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class BassUpdate(LoginRequiredMixin, UpdateView):
  model = Bass
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['manufacturer', 'model_name', 'description']

class BassDelete(LoginRequiredMixin, DeleteView):
  model = Bass
  success_url = '/basses/'

#! amp views
@login_required
def amps_index(request):
  amps = Amp.objects.all()
  # amps = Amp.objects.filter(user=request.user)
  return render(request, 'amps/index.html', {'amps': amps})

class AmpCreate(CreateView):
  model = Amp
  fields = ['manufacturer', 'model_name', 'description']
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

@login_required
def amps_detail(request, amp_id):
  amp = Amp.objects.get(id=amp_id)
  return render(request, 'amps/detail.html', {'amp':amp})
  
class AmpUpdate(LoginRequiredMixin, UpdateView):
  model = Amp
  fields = ['manufacturer', 'model_name', 'description']

class AmpDelete(LoginRequiredMixin, DeleteView):
  model = Amp
  success_url = '/amps/'

class Home(LoginView):
  template_name = 'home.html'
  

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in
      login(request, user)
      return redirect('basses_index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)
  # Same as: return render(request, 'signup.html', {'form': form, 'error_message': error_message})

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/about.css' %}"
/>
{% endblock %}
{% block content %}
<div id='about-container'>
  <img src="https://images.unsplash.com/photo-1543060749-aa3f115aad09?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" alt="bass guitars">
  <article>
    <h1>About Bass Collector</h1>
    <h2>Collect Bass Guitars and Amplifiers</h2>
    <p>Created by Patrick Cheung</p>
    <a target="_blank" rel="noopener noreferrer" href="https://github.com/thepika206/bass-collector">
      <button class="btn submit">
        View on GitHub
      </button>
    </a>
  </article>
  
</div>


{% endblock %}

main_app/templates/amps/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/amps/amp-detail.css' %}"
/>
{% endblock %}

{% block content %}

<section class="container">
  <div class="amp-img">
    <img 
      src="{% static 'images/amps/svt-200.png' %}" 
      alt="A bass amp"
    >
  </div>
  <div class="details">
    <h1>{{ amp.manufacturer }}-{{ amp.model_name }}</h1>
    <p>{{ amp.description }}</p>
    {% if amp.user == user %}
      <h3>this amp was created by you</h3>
      <div class="actions">
        <a href="{% url 'amps_update' amp.id %}" class="btn warn">Edit</a>
        <a href="{% url 'amps_delete' amp.id %}" class="btn danger">Delete</a>
      </div>
    {% else %}
      <h3>this amp was created by {{amp.user}}</h3>
    {% endif %}
  </div>
</section>

{% endblock %}

main_app/templates/amps/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/amps/amp-index.css' %}"
/>
{% endblock %}

{% block content %}


<h1>Amps List</h1>
<section class="card-container">
  {% for amp in amps %}
    <div class="card">
      <a href="{% url 'amps_detail' amp.id %}">
        <div class="card-content">
          <div class="card-img-container">
          </div>
          <h2 class="card-title">{{ amp.manufacturer }}-{{ amp.model_name }}</h2>
          <p>{{ amp.description }}</p>
          <h4>Owner: {{ amp.user }}</h4>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/favicon-16x16.png' %}"
  >
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <title>Bass Collector</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class='header-logo-container'>
      <a href="/">
        <img 
        id = "brand-logo"
        src="{% static 'images/bass-collector1.png' %}"
        alt="The Bass Collector Logo"
        >
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'basses_index'%}">Basses</a></li>
          <li><a href="{% url 'basses_create'%}">Add a Bass</a></li>
          <li><a href="{% url 'amps_index'%}">Amps</a></li>
          <li><a href="{% url 'amps_create'%}">Add an Amp</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'logout' %}">{{user}} - Log out</a></li>
        {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/basses/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
rel="stylesheet" 
type="text/css" 
href="{% static 'css/basses/bass-detail.css' %}"
/>
{% endblock %}

{% block content %}

<section class="bass-container">
  <div class="bass-img">
    <img
    id="bass-image"
    src="{% static 'images/basses/fender-jazz-200.png' %}" 
    alt="A bass guitar"
    >
  </div>
  <div class="bass-details">
    <h1>{{ bass.manufacturer }}-{{ bass.model_name }}</h1>
    <p>{{ bass.description }}</p>
    {% if bass.user == user %}
      <div class="bass-actions">
        <a href="{% url 'basses_update' bass.id %}" class="btn warn">Edit</a>
        <a href="{% url 'basses_delete' bass.id %}" class="btn danger">Delete</a>
      </div>
    {% else %}
      <h3>This bass is owned by {{bass.user}}</h3>
    {% endif %}
  </div>
</section> 
{% comment %} end of bass section {% endcomment %}

<div class="endorsement-amp-container">
  <section class="endorsements">
    <div class="subsection-title">
      <h2>Artist Endorsements</h2>
      <img 
      src="{% static 'images/favicon-32x32.png' %}" 
      alt="bass guitar"
      />
    </div>

    {% if bass.user == user %}
      <h3>Add an Artist</h3>
      <form
      action="{% url 'add_musician' bass.id %}"
      method="post" 
      class="subsection-content"
      >
        {% csrf_token %}
        {{ musician_form.as_p }}
        <button type="submit" class="btn submit">Add Endorsement</button>
      </form>
    {% endif %}

    <h3>Endorsement List</h3>
    <table>
      <thead>
        <tr><th>Artist Name</th></tr>
      </thead>
      <tbody>
        {% for musician in bass.musician_set.all %}
        <tr>
          <td>{{musician.name}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>

  {% if bass.user == user  %}
    <section class="amps">
      <div class="subsection-title">
          <h2>Plug into an Amp</h2>
      </div>
      <div class="subsection-content">
        {% if bass.amps.count %}
          {% for amp in bass.amps.all %}
            <div class="amp-container">
              <div 
              class="color-block"
              style="background-color: blue"
              ></div>
              <a href="{% url 'amps_detail' amp.id %}">
                <p>{{ amp.manufacturer }} {{ amp.model_name }}</p>
              </a>
            </div>
          {% endfor %}
        {% else %}
          <p class="no-amps">the bass isn't plugged into any amps 😞</p>
        {% endif %}
      </div>
      <h3>Available Amps</h3>
      <div class="subsection-content">
        {% if amps.count %}
          {% for amp in amps.all %}
            <div class="amp-container">
              <div 
              class="color-block"
              style="background-color: red"
              ></div>
              <a href="{% url 'amps_detail' amp.id %}">
                <p>{{ amp.manufacturer }} {{ amp.model_name }}</p>
              </a>
              <form action="{% url 'assoc_amp' bass.id amp.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Connect</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
          <p class="all-amps">
            {{bass.model_name}} is already connected to all amps 🥳
          </p>
        {% endif %}
      </div>
    </section>
  {% endif %} 
  {% comment %} "bass.user == user" {% endcomment %}
</div> 
{% comment %} "endorsement-amp-container" {% endcomment %}

    {% endblock %}

main_app/templates/basses/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/basses/bass-index.css' %}"
/>
{% endblock %}

{% block content %}

  <h1>Bass List</h1>
  {% if basses %}
    <section class="card-container">
      {% for bass in basses %}
        <div class="card">
          <a href="{% url 'basses_detail' bass.id %}">
            <div class="card-content">
              <div class="card-img-container">
                {% comment %} <img 
                    src="{% static '/images/freestocks-Fx5rrxSaUtI-unsplash.jpg' %}"
                    alt="A bass guitar"
                  > {% endcomment %}
                <img 
                  src="{% static 'images/basses/fender-jazz-200.png' %}" 
                  alt="A bass amp"
                >  
              </div>
              <h2 class="card-title">{{ bass.manufacturer }}-{{ bass.model_name }}</h2>
              <p>{{ bass.description }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </section>
  {% else %}
    <h2>No basses in your collection yet.</h2>
  {% endif %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section id="logo-container">
    <img id="home-image" src="{% static 'images/oleg-ivanov-G_3NA_UoVyo-unsplash.jpg' %}" alt="A bass guitar" />
</section>

{% if not user.is_authenticated %} 
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}
{% endblock %}

main_app/templates/main_app/amp_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Amp?</h1>
</div>
<h2>Are you sure you want to delete {{ amp.manufacturer }}-{{amp.model_name}}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'amps_detail' amp.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/amp_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}


{% if amp %}
  <h1>Edit {{ amp.manufacturer}}-{{amp.model_name}}</h1>
{% else %}
  <h1>Add an Amp</h1>
{% endif %}

{% comment %} 
  Leaving the action empty makes the form post to the same url used to display it
{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 
    Django requires the following for security purposes
  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}
      Render the inputs inside of <tr>s & <td>s
    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/bass_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Bass?</h1>
</div>
<h2>Are you sure you want to delete {{ bass.manufacturer }}-{{bass.model_name}}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'basses_detail' bass.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/bass_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

{% if bass %}
  <h1>Edit {{ bass.manufacturer}}-{{bass.model_name}}</h1>
{% else %}
  <h1>Add a Bass</h1>
{% endif %}
{% comment %} 
  Leaving the action empty makes the form post to the same url used to display it
{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 
    Django requires the following for security purposes
  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}
      Render the inputs inside of <tr>s & <td>s
    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/bass-horizontal.svg' %}" alt="A bass guitar"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}